export const sampleCampaigns = [
    {
        id: 1,
        title: "Legal Aid for Protesters",
        description: "Support activists facing legal challenges by funding their defense.",
        raisedAmount: 75000,
        goalAmount: 200000,
    },
    {
        id: 2,
        title: "Community Cleanup & Restoration",
        description: "Fund resources for volunteers restoring public spaces after protests.",
        raisedAmount: 40000,
        goalAmount: 100000,
    },
    {
        id: 3,
        title: "Emergency Relief for Displaced Activists",
        description: "Help activists who have lost homes or jobs due to their advocacy efforts.",
        raisedAmount: 60000,
        goalAmount: 150000,
    },
    {
        id: 4,
        title: "Women’s Rights Advocacy",
        description: "Support campaigns fighting for gender equality and legal protections.",
        raisedAmount: 50000,
        goalAmount: 180000,
    },
    {
        id: 5,
        title: "Environmental Justice Fund",
        description: "Help local communities resist pollution and corporate environmental damage.",
        raisedAmount: 120000,
        goalAmount: 300000,
    },
    {
        id: 6,
        title: "Journalists at Risk Support Fund",
        description: "Protect independent journalists and whistleblowers under threat.",
        raisedAmount: 80000,
        goalAmount: 250000,
    },
    {
        id: 7,
        title: "Education for Underprivileged Kids",
        description: "Provide school supplies and educational resources for marginalized children.",
        raisedAmount: 95000,
        goalAmount: 200000,
    },
    {
        id: 8,
        title: "Disaster Relief for Refugees",
        description: "Fund emergency food, shelter, and medical aid for displaced refugees.",
        raisedAmount: 150000,
        goalAmount: 500000,
    },
    {
        id: 9,
        title: "Tech for Activists Initiative",
        description: "Provide secure devices and encryption tools to activists in surveillance-heavy areas.",
        raisedAmount: 70000,
        goalAmount: 250000,
    },
    {
        id: 10,
        title: "Mental Health Support for Activists",
        description: "Fund therapy and support groups for activists experiencing burnout.",
        raisedAmount: 55000,
        goalAmount: 150000,
    }
];
