export const sampleVideos = [
  {
    id: 1,
    title: "Youth Activism Workshop: Creating Change",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfYTtQgouUK_GZR3rZs_2kH8tecmrxX8SQ7w&s",
    videoUrl: "https://www.youtube.com/watch?v=ACTIVISM_VIDEO_1",
    views: "1.2M views",
  },
  {
    id: 2,
    title: "Power of Storytelling in Social Change",
    thumbnail: "https://www.muralarts.org/wp-content/uploads/2016/09/2014-048_OS_FAIREY_PMA_011.jpg",
    views: "900K views",
  },
  {
    id: 3,
    title: "Sustainable Living: A Panel Discussion",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFosM511FbNtx1aotS4HhC18raD0lc-UUWLQ&s",
    videoUrl: "https://www.youtube.com/watch?v=SUSTAINABILITY_VIDEO_3",
    views: "1.5M views",
  },
  {
    id: 4,
    title: "Women in Activism: Voices for Equality",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsE826ndr4Yl-Pwkv3c_vhNHENdCmLMwdTaw&s",
    videoUrl: "https://www.youtube.com/watch?v=WOMEN_ACTIVISM_VIDEO_4",
    views: "2.1M views",
  },
  {
    id: 5,
    title: "Climate Crisis: Expert Talk & Solutions",
    thumbnail: "https://guisegarner.com/wp-content/uploads/2024/01/sustainability.webp",
    videoUrl: "https://www.youtube.com/watch?v=CLIMATE_TALK_VIDEO_5",
    views: "3.4M views",
  },
  {
    id: 6,
    title: "Breaking Barriers: Art for Social Good",
    thumbnail: "https://media.sva.edu/image/upload/c_scale,f_auto,dpr_auto,q_auto,w_768/multimediaBlock/2b251ca4cc40477432e16bb9ebda9c8e994bdca3-1595496633.jpeg",
    videoUrl: "https://www.youtube.com/watch?v=ART_SOCIAL_GOOD_VIDEO_6",
    views: "1.7M views",
  },
  {
    id: 7,
    title: "Technology & Human Rights: A Debate",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-ff8S9dOStznid0GbZ53a10oygGVsoPiVLA&s",
    videoUrl: "https://www.youtube.com/watch?v=TECH_HUMAN_RIGHTS_VIDEO_7",
    views: "2.6M views",
  },
  {
    id: 8,
    title: "Community Impact: Grassroots Leaders Speak",
    thumbnail: "https://img.freepik.com/free-vector/business-people_53876-25444.jpg",
    videoUrl: "https://www.youtube.com/watch?v=GRASSROOTS_VIDEO_8",
    views: "850K views",
  },
];
